### ISSUE TITLE
more error reasons to abort `retry`

### ISSUE THREAD

**Issue by easz** [public-transport/hafas-client#227]
Sometimes hafas client can fail due to invalid date/time (e.g. query data/time outside the 'Fahrplanperiode'), in this case there is no reason to retry. There would be more reasons to abort.

Therefore, `ENOTFOUND` is not the only reason to abort the rety.

https://github.com/public-transport/hafas-client/blob/e9701648eeaf8c4e3a0f53c202d0f3bcd29ff954/retry.js#L22

btw, where can I get the overview of all possible error code?

**Comment by derhuerst** [comment]
Thanks for pointing this out.

The retry handling is a bit inconsistent right now; I added the `ENOTFOUND` abort mainly with network-level errors in mind, where I want the error to "bubble up" to the caller; With a HAFAS-specific quirk however (e.g. the `reachableFrom()` call is notoriously unstable), I want to silently retry.

> Sometimes hafas client can fail due to invalid date/time (e.g. query data/time outside the 'Fahrplanperiode'), in this case there is no reason to retry.

Indeed! As an example, such a HAFAS response looks like this:

```json
{
	"ver": "1.16",
	"ext": "VBB.1",
	"lang": "eng",
	"id": "xgwicm8qi4cdpiwx",
	"svcResL": [
		{
			"meth": "StationBoard",
			"err": "H9360",
			"errTxt": "HAFAS Kernel: Date outside of the timetable period.",
			"res": {
				"common": {
					"locL": [],
					"prodL": [],
					"opL": [],
					"remL": [],
					"icoL": []
				}
			}
		}
	]
}
```

The `svcResL[0].err` code is used to expose more error details from [`lib/errors.js`](https://github.com/public-transport/hafas-client/blob/e9701648eeaf8c4e3a0f53c202d0f3bcd29ff954/lib/errors.js). This means that, in the "outside of the Fahrplanperiode" case, the error will have a field `code` with `INVALID_REQUEST`.

I guess it would only have to retry on *unknown* errors or `SERVER_ERROR` errors. I will investigate this.

**Comment by easz** [comment]
I thought `ENOTFOUND` means that the hafas server cannot find a valid transport connection (e.g. cannot find station or stop around the given coordinates)

I would generally by default only `retry` if there is a network communication issue, and the application level error should bubble up to the caller.

**Comment by derhuerst** [comment]
> I thought `ENOTFOUND` means that the hafas server cannot find a valid transport connection (e.g. cannot find station or stop around the given coordinates)

No, `ENOTFOUND` is an error code of the [`getaddrinfo` syscall](https://en.wikipedia.org/wiki/Getaddrinfo).

> I would generally by default only `retry` if there is a network communication issue, and the application level error should bubble up to the caller.

Huh, that's another way to look at it. My thought behind the current code was:

`hafas-client` should retry whenever the fault is *HAFAS-specific*, because only `hafas-client` knows that this is a request where retrying makes sense. With all other errors, e.g. network errors, the application can decide wether to retry or not.

**Comment by derhuerst** [comment]
I have closed this. Don't hesitate to reply here though if you find error handling behaviour in `hafas-client` that does not follow this idea.

**Comment by derhuerst** [comment]
I'll give an update on error handling in `hafas-client`:

While the error handling is unintuitive in `hafas-client@5` because it misses its goal of being helpful, in the upcoming `hafas-client@6`, I have tried to make it more consistent. Specifically, in a3421cf99a9fa4ef25d67db170337967f5e022d1, I changed all errors created by `hafas-client` (bugs in `hafas-client` aside) to be subclasses of `HafasError`. You can read more here: https://github.com/public-transport/hafas-client/tree/eede28e37210121e4a723ffcc44be6ab10fa3d8d/docs#error-handling

> To determine **if you should automatically retry an error, use `!error.causedByServer`**.
