### ISSUE TITLE
Sometimes `departure` is missing resulting in ftpf-invalid data

### ISSUE THREAD

**Issue by yu-re-ka** [public-transport/hafas-client#243]
The train doesn't have any departure or arrval timestamps. It's cancelled:
https://trainsear.ch/#/IVRSULBd/4

IMO it should be filled with plannedDeparture, because ftpf says departure is a required field.

**Comment by yu-re-ka** [comment]
[log.ndjson.txt](https://github.com/public-transport/hafas-client/files/7006443/log.ndjson.txt)

**Comment by derhuerst** [comment]
Although the readme states otherwise, `hafas-client` doesn't follow FPTF 1 exactly, sorry. Rather, it follows the FPTF 2 draft discussed in https://github.com/public-transport/friendly-public-transport-format/issues/27.

I was planning to quickly finish the FPTF 2 discussion and adapt `hafas-client@6` to whatever the outcome is.

**Comment by yu-re-ka** [comment]
If you could add a link to the draft of FPTF 2 that hafas-client follows to the readme, that would solve my issue. Otherwise we end up with an undefined format again.
