### ISSUE TITLE
HVV AKN categorized as product "regional-train".

### ISSUE THREAD

**Issue by fxb** [public-transport/hafas-client#262]
It looks like AKN trips are always returned with product `regional-train` instead of `akn`.

The same applies when requesting it via the product request parameters:

* `https://v5.hvv.transport.rest/stops/2342/departures?akn=true&regional-train=false` does wrongly NOT return AKN trips.
* `https://v5.hvv.transport.rest/stops/2342/departures?akn=false&regional-train=true` does wrongly return AKN trips.

**Comment by fxb** [comment]
I believe the same has happened with `express-bus`. All the `X<number>` buses are categorized just as `bus`. Probably since HVV got rid of their `SchnellBus` and replaced it will `XpressBus`

**Comment by derhuerst** [comment]
This might be due to

- the [HVV products'](https://github.com/public-transport/hafas-client/blob/cbc7f63dcc6a1cda3271966facc93508bd46af54/p/hvv/products.js) bitmasks not being correct/up-to-date
- a wrongly configured HAFAS server

Can you try to check if *all* AKN trips that you can find are labeled as `regional-train`? Check other stops for example.
