### ISSUE TITLE
DB: get URL to offers

### ISSUE THREAD

**Issue by PaulSut** [public-transport/hafas-client#296]
I'd like to create a URL for a specific Journey that takes me directly to the DB offers page, where I can select offers like Sparpreis and Flexpreis for a specific journey. I'm unsure about the best approach for this. Any guidance would be greatly appreciated. 

I would also be happy to contribute a function which creates the URL if there is an interest for this :)

**Comment by derhuerst** [comment]
I have looked into how the DB Navigator app does this. We can probably mimic its functionality!

Given that `hafas-client` (currently only) implements the *mobile* HAFAS API intended for *mobile devices*, we will only be able to generate links to the *mobile* DB shop. (Maybe we can reverse-engineer how to generate desktop booking links.)

*Note:* Keep in mind that there's also a ([currently half-broken](https://github.com/derhuerst/generate-db-shop-urls/issues/49), because the DB shop changes frequently) library that, given a full journey – obtained from `hafts-client`, for example –, tries to "navigate" the shop, filling in all necessary details, to get the URL of the tariff/fare selection page. It has many limitations, but it is independent of `hafas-client` because it only queries the DB shop, so it has a slightly different use case.

**Comment by derhuerst** [comment]
I have recorded the [HTTP requests of DB Navigator `v23.08.01`](https://gist.github.com/derhuerst/d790cdf8ac9a94ae7554f43890e29930). Its booking flow seems to work as follows:

For `TripSearch` (`journeys()`) and `Reconstruction` (`refreshJourney()`) requests, the response contains a [`trfRes`](https://gist.github.com/derhuerst/d790cdf8ac9a94ae7554f43890e29930#file-03-reconstruction-http-L1249-L1348) object for each journey. This `trfRes` enumerates all bookable tariffs/fares in `fareSetL[]`, and each tariff/fare has a field `addData`, which contains Base64-encoded data that is used to display details in the the tariff/fare selection screen.

For example, with the [requested journey from Berlin to Wien at `2023-09-11T06:29+02:00`](https://gist.github.com/derhuerst/d790cdf8ac9a94ae7554f43890e29930#file-03-reconstruction-http-L627-L1349) (also linked above), the "Super Sparpreis Europa" fare [contains an `addData`](https://gist.github.com/derhuerst/d790cdf8ac9a94ae7554f43890e29930#file-03-reconstruction-http-L1256) that looks like this decoded:

```json
{
	"AngTyp": "superSparP",
	"IsKBKampagne": "NO",
	"ID": "TCK#3860#3863#0#0#S2#9810#",
	"IDVerbund": "PFRhcmlmZiBUYXJpZmZJRD0iVENLIzM4NjAjMzg2MyMwIzAjUzIjOTgxMCMiIFBBcnREcml0dGU9InVua25vd24iLz4%3D%0D%0A",
	"IsVisible": "YES",
	"KoTxt_kurz.0": "",
	"KoTxt_lang.0": "Through ticket: Your ticket constitutes a continuous contract of carriage in each direction. Should you make a passenger rights claim, the ticket will be considered in its entirety.",
	"KoTxt_kurz.1": "",
	"KoTxt_lang.1": "A 3-D Secure Code may be required for credit card payments.",
	"PrioTxt_kurz.0": "Train-specific travel",
	"PrioTxt_lang.0": "You can use all trains indicated on your ticket. You can use any local train (i.e. RE, RB, S). Passengers on train services with mandatory reservation must reserve a seat.",
	"PrioTxt_icon.0": "202",
	"PrioTxt_kurz.1": "",
	"PrioTxt_lang.1": "If you choose a train service that requires a reservation, your booking includes a free seat reservation for this train service.",
	"UeTxt_kurz": "Cancellation excluded",
	"UeTxt_lang": "Cancellation (exchange or refund) of your ticket is excluded.",
	"UeTxt_icon": "202",
	"OptTxt_kurz.0": "No City-Ticket",
	"OptTxt_lang.0": "Your ticket does not include a City-Ticket (local public transport ticket).",
	"OptTxt_icon.0": "202",
	"OptTxt_key.0": "ohne_city",
	"PATyp": "AP",
	"PArtDpt": "3860",
	"ResIcon": "NO",
	"ResStatus": "O",
	"TarifSystemId": "DB",
	"ZugeordnetZuSpezialablauf": "NO",
	"Zusatznutzen": "NO"
}
```

[It's `ticketL[0].addData`](https://gist.github.com/derhuerst/d790cdf8ac9a94ae7554f43890e29930#file-03-reconstruction-http-L1261) looks like this decoded:

```json
{
	"dir": "OUTWARD",
	"type": "TICKET",
	"FromText": "Berlin Hbf (tief)",
	"ToText": "Wien Hbf",
	"FromEva": "8098160",
	"ToEva": "8103000"
}
```

The fare's `addData`'s `ID` (`TCK#3860#3863#0#0#S2#9810#`) is then being [`POST`ed url-encoded into `https://mobile.bahn.de/bin/mobil/query.exe/eox`](https://gist.github.com/derhuerst/d790cdf8ac9a94ae7554f43890e29930#file-04-shop-http), along with other details from the journey. These are the request's query parameters url-decoded:

```
A.1:             27
E:               F
E.1:             2
K:               2
M:               D
RT.1:            E
SS:              8098160
T:               202309110629
VH:              T$A=1@O=Berlin Hbf (tief)@L=8098160@a=128@$A=1@O=Nürnberg Hbf@L=8000284@a=128@$202309110629$202309110952$ICE  503$$1$$$$$$§T$A=1@O=Nürnberg Hbf@L=8000284@a=128@$A=1@O=Wien Hbf@L=8103000@a=128@$202309111031$202309111447$ICE   23$$1$$$$$$
ZS:              8103000
journeyOptions:  0
journeyProducts: 1023
optimize:        1
shpCtx:          PFRhcmlmZiBUYXJpZmZJRD0iVENLIzM4NjAjMzg2MyMwIzAjUzIjOTgxMCMiIFBBcnREcml0dGU9InVua25vd24iLz4=
returnurl:       dbnavigator://restore
```

- `VH` is directly taken from [HAFAS' `jny.ctxRecon`](https://gist.github.com/derhuerst/d790cdf8ac9a94ae7554f43890e29930#file-03-reconstruction-http-L695) (`refreshToken` in `hafas-client`).
- `shpCtx`'s value Base64-decoded is `<Tariff TariffID="TCK#3860#3863#0#0#S2#9810#" PArtDritte="unknown"/>`.
- Other parameters likely follow the semantic model implemented by [`generate-db-shop-url`](https://github.com/derhuerst/generate-db-shop-urls), so we can probably take some hints from there.

**Comment by derhuerst** [comment]
What needs to be done:

- [ ] In the DB profile, for `journeys()` & `refreshJourney()`, implement a new flag `opt.dbShopUrls` that toggles the generation of DB shop tariff/fare selection URLs.
- [ ] If `opt.dbShopUrls` is `true`, in the [DB profile's existing tariff/fare parsing logic](https://github.com/public-transport/hafas-client/blob/0bc6ba36508eb463c68d92731a79314ee4d7311b/p/db/index.js#L276-L291), for each tariff/fare,
	1. decode its `addData`, obtain the `ID`;
	2. obtain all other relevant details from the journey (`VH` a.k.a. `ctxRecon`, `SS` a.k.a. the origin stop ID, `T` a.k.a. departure date+time, etc.)
	3. generate a `/bin/mobil/query.exe/eox` URL containing all necessary query parameters url-encoded
	4. expose this URL as e.g. `journey.fares[].dbShopUrl`.
- [ ] Verify that all of this works, and write a test for it.

**Comment by derhuerst** [comment]
A heads-up: Implementing this feature will require some familiarity with the way the `hafas-client` code base is structured. Nevertheless, you're welcome to ask questions if you get stuck!

**Comment by PaulSut** [comment]
Thank you very much for the input! Super nice of you! 
I will investigate it next week and get familiar with the code base :)

**Comment by derhuerst** [comment]
> `journeys()` & `refreshJourney()` seems to return a different `fareSetL[]`.

Can you elaborate? Or even provide two raw responses? (You can obtain them by running `./tools/debug-cli/cli.js db …` with `DEBUG=hafas-client`.)

**Comment by PaulSut** [comment]
Thanks for pointing out the DEBUG mode :) 

It seems like the 'fareSetL[]' differ when using [TripSearch](https://gist.github.com/derhuerst/d790cdf8ac9a94ae7554f43890e29930#file-01-tripsearch-http-L1735-L1751) or [Reconstruction](https://gist.github.com/derhuerst/d790cdf8ac9a94ae7554f43890e29930#file-02-reconstruction-http-L1250-L1269) (e.g. only Reconstruction containing `addData`) 
I get a similar Result to TripSearch when using [journeys()](https://gist.github.com/PaulSut/0fb9bc56c44382f5c4fc3e62d71c884f#file-hafas-client-debug-journeys-01-http-L506-L524), but no fares when using [refreshJourney()](https://gist.github.com/PaulSut/0fb9bc56c44382f5c4fc3e62d71c884f#file-hafas-client-debug-refreshjourney-01-http-L395-L413)

I added the used commands at the top of each file in case I am using them wrong.

**Comment by derhuerst** [comment]
Did you specify `opt.age`? Does it depend on that?

**Comment by PaulSut** [comment]
I had to dig a little deeper but i found the issue now :) 

The `trfReq` with the right params was missing for the "Reconstruction" request. 
I will try to create a draft PR which implements the needed changes to get the offers from DB soonish. 
Afterwards I will have a look into the URL-Topic.

**Comment by PaulSut** [comment]
After looking deeper into the URL topic I am pretty sure that there will be more changes regarding the output format which is why I closed the PR for now. I will incorporate the changes in a future PR :)

**Comment by derhuerst** [comment]
From #297:

> I adjusted the output format, which leads to a breaking change for users of p/db.

Keep in mind that I try to minimise the breaking changes (and thus major-version releases) in `hafas-client`; I try to do a major release every 2 years (in that order of magnitude, not a strict cycle).

So if it's possible with reasonable effort, try to keep your changes backwards-compatible, by adding all newly parsed information as a new field. Later, we can refactor the format as a breaking change.

**Comment by PaulSut** [comment]
[This](https://github.com/PaulSut/hafas-client/tree/non-breaking-db-tickets) is a non breaking version that enables to get fares and the url to each fare via `refreshJourney()`. Everything seems to work fine so far, but I did not fully understand all the params yet. Also, the current url is leading to the "old" DBNavigator. I am not sure if it is also possible to get the link for the new one. 
Maybe I will find more time to look into it, therefore i would not merge it right now to prevent breaking changes/workarounds in case of better solutions (suggestions regarding the [missings params](https://github.com/PaulSut/hafas-client/blob/69b6d117cad017fdcd69f1aac1cf675fe7d793e3/p/db/index.js#L245) or the new DBNavigator link are very welcome :))

**Comment by derhuerst** [comment]
Again: Thanks for you effort in reverse-engineering and implementing this! I think this is a very useful addition to `hafas-client`. 💛

Unfortunately, the commits currently change too many unrelated things for me to feel comfortable to merge them as-is, for example:

- lots of unrelated whitespace/indentation changes – While these theoretically don't bother much, they later make blaming & diffing much harder. It frequently do this to find out when & *why* something has been changed, often with my own changes too, simply because I don't remember anymore. Having focused and [as-atomic-as-possible commits](https://www.aleksandrhovhannisyan.com/blog/atomic-git-commits/) makes this a lot easier.
- In `getDbOfferSelectionUrl()`, you should use [`url.searchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams) to add all those query parameters to the offer selection URL. It is safer (because you can't forget to URL-encode them when changing things later) and IMHO a bit more readable.
- As you may have noticed, I tend to keep quite a lot of "todo" comments in the code, to keep track (admittedly in a very unapproachable way) of possible enhancements and half-reverse-engineered bits of logic. Your changes remove two of these ([1](https://github.com/public-transport/hafas-client/compare/449d2261bd6818f9813c5337e356804a7ecd9009...PaulSut:hafas-client:69b6d117cad017fdcd69f1aac1cf675fe7d793e3#diff-c25b2fbd44a95d9af4e3b81fbc961b725fbd378e555105d5951e251a4399c02dL231-L232), [2](https://github.com/public-transport/hafas-client/compare/449d2261bd6818f9813c5337e356804a7ecd9009...PaulSut:hafas-client:69b6d117cad017fdcd69f1aac1cf675fe7d793e3#diff-c25b2fbd44a95d9af4e3b81fbc961b725fbd378e555105d5951e251a4399c02dL235-L275)) which I would like to keep, given that the new code doesn't parse the fields mentioned in them.
- some minor naming things, e.g. naming mutations functions "get…" – I would certainly merge them anyways if they were the sole nitpicks I had about a set of commits! But given that I requested other changes above, I'm letting you know.

If you want, I can try to find time to bring your changes into the shape I want them to be in and merge them. (I will make sure to keep you as the author or co-author in the resulting commits, so that you will appear as a contributor to `hafas-client`.)

On the other hand, if you're planning to change the code *anyways*, in one way or another, I will first let you finish iterating on it, and then review it again.

What do you think?

**Comment by PaulSut** [comment]
Unfortunately not really :/ 
Tickets contain now also a `firstClass` info, but the ticket-url is still not really usable and I couldn't fix it. I will have a closer look into this before new year.

**Comment by PaulSut** [comment]
I created a new [PR](https://github.com/public-transport/hafas-client/pull/310) which adds the ticket information. 

I am rather pessemistic regarding the URL. The [generated URLs](https://github.com/PaulSut/hafas-client/tree/non-breaking-db-tickets) 'kind of work'. But not with every device/browser/cookie combination and therefore imo not reliable enough to add it to the hafas client. Even if the link works it is not really user friendly

**Comment by derhuerst** [comment]
> I am rather pessemistic regarding the URL. The [generated URLs](https://github.com/PaulSut/hafas-client/tree/non-breaking-db-tickets) 'kind of work'. But not with every device/browser/cookie combination and therefore imo not reliable enough to add it to the hafas client. Even if the link works it is not really user friendly

We could put them behind an opt-in flag, e.g. `generateUnreliableTicketUrls`. What do you think?

**Comment by PaulSut** [comment]
> We could put them behind an opt-in flag, e.g. `generateUnreliableTicketUrls`. What do you think?

This and your suggested changes are now implemented :)
