### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by paha77** [public-transport/hafas-client#309]
I'm trying to create a client within an nestjs-console command:

```typescript
import { createClient } from "hafas-client";
import { profile as dbProfile } from "hafas-client/p/db/index.js";
// ...
async testCommand(): Promise<void> {
        const client = createClient(dbProfile, "https://github.com/paha77");
}
```

but get the following error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module <MY PROJECT ROOT>node_modules/hafas-client/index.js from <MY PROJECT ROOT>src/hafas/hafas.console.ts not supported.
Instead change the require of index.js in <MY PROJECT ROOT>src/hafas/hafas.console.ts to a dynamic import() which is available in all CommonJS modules.
```

**Comment by derhuerst** [comment]
AFAICT, this is nothing that `hafas-client` has control over, so I can't help you, sorry.

Using the [`type: module` directive](https://nodejs.org/api/packages.html#type), it denotes itself as an [ESM](https://nodejs.org/api/esm.html#modules-ecmascript-modules) package.

It seems like your code is getting transpiled to `require()` calls, which then fails because `hafas-client` is not getting transpiled (and because Node's `require()` does not support ESM).
