### ISSUE TITLE
Two canceled properties

### ISSUE THREAD

**Issue by flori-uni** [public-transport/hafas-client#82]
There are atm to properties representing a canceled trip. (one spelled canceled one cancel**l**ed)
Are really both required? 😄 

https://github.com/public-transport/hafas-client/blob/c6b7aa74ddef57c5531623b95f6f70333368f34f/parse/arrival-or-departure.js#L52

**Comment by derhuerst** [comment]
> Are really both required? 😄

Nope, they're not.

I weighed usability (supporting American English and British English, because both forms of "canceled" are seen often) and semantics (two properties for the same thing is kind of ugly) and ended up with better usability. See also public-transport/friendly-public-transport-format#27.

The `canceled` prop is defined a non-enumerable, so that you won't have two props when looping over the object's keys or creating JSON from it.

Do you still disagree?

**Comment by flori-uni** [comment]
Well okay. Got the point.

**Comment by derhuerst** [comment]
I'm willing to consider removing this in `hafas-client@4`.
